const CATS = [
  { id: 'general', name: 'Información General', color: '#2e9be0' },
  { id: 'estructura', name: 'Estructura', color: '#38b6a0' },
  { id: 'funcionamiento', name: 'Funcionamiento', color: '#f0536b' },
  { id: 'caso', name: 'Caso Práctico', color: '#9b6dd6' },
  { id: 'ventajas', name: 'Ventajas y Limitaciones', color: '#e8a33d' }
];

const QUESTIONS = {
  general: [
    { q: "¿Cuál es el propósito central de ISO/IEC 27002?",
      opts: ["Ofrecer un conjunto de referencia de controles de seguridad, ciberseguridad y protección de la privacidad",
             "Imponer requisitos obligatorios para todas las organizaciones",
             "Sustituir a las normas contables internacionales",
             "Certificar productos de software"], a: 0 },
    { q: "¿Quiénes desarrollan la norma ISO/IEC 27002?",
      opts: ["ISO y IEC, por medio del comité técnico ISO/IEC JTC 1/SC 27",
             "Solo la Unión Europea", "Naciones Unidas",
             "El Ministerio de Tecnologías de cada país"], a: 0 },
    { q: "¿De qué código de prácticas se origina ISO/IEC 27002?",
      opts: ["BS 7799-1 del Reino Unido", "COBIT", "ITIL", "PCI DSS"], a: 0 },
    { q: "¿Cómo se llamó la norma cuando fue adoptada como estándar internacional en el año 2000?",
      opts: ["ISO/IEC 17799", "ISO/IEC 27001", "ISO 9001", "ISO/IEC 27005"], a: 0 },
    { q: "¿En qué año fue renombrada como ISO/IEC 27002?",
      opts: ["2007", "1995", "2015", "2020"], a: 0 },
    { q: "¿Cuál es la versión vigente de ISO/IEC 27002?",
      opts: ["La tercera edición, publicada en febrero de 2022",
             "La primera edición de 1995", "La edición de 2013", "La edición de 2016"], a: 0 },
    { q: "¿ISO/IEC 27002 es certificable o de cumplimiento obligatorio?",
      opts: ["No, es una guía de buenas prácticas que no impone requisitos obligatorios",
             "Sí, obligatoria para todas las empresas",
             "Sí, pero solo para bancos",
             "No, es una norma contable opcional"], a: 0 },
    { q: "¿Cuáles son los tres principios de seguridad que busca proteger la información?",
      opts: ["Confidencialidad, integridad y disponibilidad",
             "Velocidad, costo y tamaño", "Precio, marca y calidad",
             "Diseño, estética y usabilidad"], a: 0 },
    { q: "¿A qué tipo de organizaciones puede aplicarse ISO/IEC 27002?",
      opts: ["A cualquier tamaño y sector: públicas y privadas",
             "Solo a grandes corporaciones", "Solo a empresas de tecnología",
             "Únicamente a organismos gubernamentales"], a: 0 },
    { q: "¿Qué relación tienen ISO/IEC 27001 e ISO/IEC 27002?",
      opts: ["27001 define qué debe cumplirse; 27002 explica cómo implementarlo en la práctica",
             "Son la misma norma con nombres distintos",
             "27002 es la versión antigua de 27001",
             "No tienen ninguna relación"], a: 0 },
    { q: "¿Qué diferencia una norma de requisitos de una guía de buenas prácticas?",
      opts: ["La 27001 es certificable y la 27002 es una guía no certificable",
             "La 27001 no exige nada y la 27002 sí",
             "Ambas son igual de obligatorias",
             "La 27002 otorga el sello de certificación"], a: 0 }
  ],
  estructura: [
    { q: "¿Cuántos controles organiza ISO/IEC 27002:2022 en total?",
      opts: ["93 controles", "50 controles", "14 controles", "120 controles"], a: 0 },
    { q: "¿En cuántas categorías se organizan los controles de ISO/IEC 27002:2022?",
      opts: ["4: organizacionales, de personas, físicos y tecnológicos",
             "7 categorías", "2: informáticos y manuales", "14 dominios"], a: 0 },
    { q: "¿Cuántos controles organizacionales tiene la norma?",
      opts: ["37", "8", "14", "93"], a: 0 },
    { q: "¿Cuántos controles relacionados con las personas incluye?",
      opts: ["8", "37", "34", "14"], a: 0 },
    { q: "¿Cuántos controles físicos contempla?",
      opts: ["14", "8", "37", "34"], a: 0 },
    { q: "¿Cuántos controles tecnológicos son parte de la norma?",
      opts: ["34", "37", "14", "8"], a: 0 },
    { q: "¿Qué es un control de seguridad de la información?",
      opts: ["Una medida que mantiene o modifica un riesgo de seguridad de la información",
             "Solo una herramienta informática",
             "Un software antivirus obligatorio",
             "Un procedimiento de compra"], a: 0 },
    { q: "¿Cuál es un ejemplo de control organizacional?",
      opts: ["La política de seguridad de la información",
             "El uso de tarjetas de acceso a instalaciones",
             "El cifrado de información", "La autenticación multifactor"], a: 0 },
    { q: "¿Qué controles se relacionan con la selección de personal y la concientización?",
      opts: ["Los controles de personas", "Los controles físicos",
             "Los controles tecnológicos", "Los controles contables"], a: 0 },
    { q: "¿Qué es la política de 'escritorio y pantalla limpios'?",
      opts: ["Un control físico para evitar exponer información sensible en áreas de trabajo",
             "Un control para mantener limpias las computadoras por dentro",
             "Una norma de higiene personal", "Un requisito para reciclar equipos"], a: 0 },
    { q: "¿Cómo se llamaba la estructura previa de la norma antes de la reorganización de 2022?",
      opts: ["Catorce dominios", "Cuatro cláusulas", "Diez procesos", "Cinco fases"], a: 0 },
    { q: "¿Cuál es un ejemplo de control tecnológico?",
      opts: ["La autenticación multifactor o el cifrado de información sensible",
             "La política de escritorio limpio",
             "La asignación de roles y responsabilidades",
             "La selección de antecedentes del personal"], a: 0 }
  ],
  funcionamiento: [
    { q: "¿Cómo se utilizan los controles de ISO/IEC 27002?",
      opts: ["Se eligen según los riesgos de cada organización, no todos a la vez ni al azar",
             "Todos deben aplicarse obligatoriamente el primer día",
             "Solo se aplican después de un incidente",
             "Se eligen por sorteo"], a: 0 },
    { q: "¿En qué se basa la selección de los controles?",
      opts: ["En un proceso de gestión de riesgos de seguridad de la información",
             "En el presupuesto de marketing", "En las sugerencias de los clientes",
             "En la cantidad de empleados"], a: 0 },
    { q: "¿Cuál es el paso inicial para seleccionar controles?",
      opts: ["Identificar y analizar los riesgos que afectan los activos de información",
             "Comprar más software", "Contratar una auditoría externa",
             "Certificar la empresa"], a: 0 },
    { q: "¿Qué norma de apoyo se usa para priorizar controles tecnológicos mediante evaluación de riesgos?",
      opts: ["ISO/IEC 27005", "ISO 9001", "ISO 14001", "ISO/IEC 27002 en solitario"], a: 0 },
    { q: "¿Cuál es el orden correcto del proceso de implementación?",
      opts: ["Evaluación de riesgos → selección de controles → planificación → asignación de responsables y recursos → implementación → seguimiento y revisión → mejora continua",
             "Implementación → compra de equipos → evaluación → certificación",
             "Selección → implementación → evaluación al final",
             "Evaluación → certificación → implementación"], a: 0 },
    { q: "¿Quiénes participan en la implementación de los controles?",
      opts: ["Todas las áreas de la organización, no solo TI",
             "Únicamente el departamento de tecnología",
             "Solo la gerencia general", "Solo consultores externos"], a: 0 },
    { q: "¿De qué dependen los recursos necesarios para implementar la norma?",
      opts: ["De los riesgos identificados y de los controles que la organización decida implementar",
             "De un monto fijo establecido por ISO", "Del número de sucursales",
             "Del tamaño de la facturación"], a: 0 },
    { q: "¿Cómo contribuyen los controles a reducir el riesgo?",
      opts: ["Modificando el riesgo: reduciendo la probabilidad de incidentes o sus consecuencias",
             "Eliminando toda posibilidad de ataque", "Aumentando los costos de seguridad",
             "Tercerizando toda la seguridad"], a: 0 },
    { q: "¿La implementación de ISO/IEC 27002 se limita solo a instalar herramientas informáticas?",
      opts: ["No, incluye políticas, procesos, personas y medidas físicas",
             "Sí, solo se instala software", "Sí, solo se compran servidores",
             "No, solo se hacen capacitaciones"], a: 0 },
    { q: "¿Qué permite el enfoque basado en riesgos?",
      opts: ["Que la seguridad sea proporcional al riesgo y se eviten controles innecesarios",
             "Que todos apliquen los 93 controles siempre",
             "Que no se evalúen riesgos nunca",
             "Que se ignore el contexto de la organización"], a: 0 }
  ],
  caso: [
    { q: "En el caso práctico, ¿qué debilidad se detecta en la institución educativa?",
      opts: ["Cuentas compartidas, contraseñas débiles, cuentas de antiguos trabajadores activas y falta de revisión de permisos",
             "Falta de presupuesto en computadoras", "Ausencia de red wifi",
             "Demasiadas copias de respaldo"], a: 0 },
    { q: "¿Cuál es el principal riesgo en el caso de la institución?",
      opts: ["Que una persona no autorizada acceda al sistema con una cuenta ajena o con permisos que debieron eliminarse",
             "Que se caiga el internet", "Que se apaguen las luces",
             "Que los estudiantes copien en los exámenes"], a: 0 },
    { q: "Si una persona no autorizada consulta información, ¿qué principio de seguridad se afecta?",
      opts: ["La confidencialidad", "La integridad", "La disponibilidad", "El rendimiento"], a: 0 },
    { q: "Si se modifican las notas de los estudiantes indebidamente, ¿qué principio se afecta?",
      opts: ["La integridad", "La confidencialidad", "La disponibilidad", "La usabilidad"], a: 0 },
    { q: "Si la información es eliminada o queda inaccesible, ¿qué principio se afecta?",
      opts: ["La disponibilidad", "La integridad", "La confidencialidad", "La escalabilidad"], a: 0 },
    { q: "¿Cuál de estas es una medida propuesta para el caso?",
      opts: ["Cuenta de usuario individual y única para cada trabajador",
             "Compartir la misma contraseña entre todos",
             "Eliminar todos los respaldos",
             "Dejar los permisos de antiguos trabajadores activos"], a: 0 },
    { q: "¿Qué se debe hacer con los derechos de acceso cuando una persona cambia de puesto o deja la institución?",
      opts: ["Revisarlos y eliminarlos oportunamente", "Mantenerlos para siempre",
             "Regalarlos a otro empleado", "Ignorarlos"], a: 0 },
    { q: "¿Qué medida de autenticación se recomienda en el caso?",
      opts: ["Autenticación multifactor y contraseñas robustas y únicas",
             "Usar la misma contraseña para todo", "No usar contraseñas",
             "Contraseñas cortas y simples"], a: 0 },
    { q: "¿Por qué se recomiendan copias de respaldo periódicas?",
      opts: ["Para recuperar la información ante pérdida o eliminación",
             "Para ocupar espacio en disco", "Para duplicar los costos",
             "Para aumentar la velocidad"], a: 0 },
    { q: "¿Cómo se asignarían los permisos según la medida propuesta?",
      opts: ["Con base en las funciones laborales de cada individuo",
             "Por antigüedad en la empresa", "Al azar",
             "A todos por igual sean quienes sean"], a: 0 }
  ],
  ventajas: [
    { q: "¿Cuál es una de las principales ventajas de ISO/IEC 27002?",
      opts: ["Proporciona un marco amplio y estructurado de controles de seguridad",
             "Es ilegal no usarla", "Garantiza que nunca habrá ataques",
             "Reemplaza cualquier otra norma"], a: 0 },
    { q: "¿Qué contribuye a hacer ISO/IEC 27002 respecto del riesgo?",
      opts: ["Gestionar y reducir los riesgos mediante controles preventivos basados en riesgos",
             "Esperar a que ocurran los incidentes para actuar",
             "Eliminar los costos de seguridad", "Transferir el riesgo al Estado"], a: 0 },
    { q: "¿Por qué se dice que la norma es flexible y adaptable?",
      opts: ["Porque sirve a organizaciones de diferentes tamaños y sectores, adaptando los controles a su contexto",
             "Porque obliga a todas igualmente",
             "Porque solo sirve a las grandes empresas",
             "Porque no permite cambios"], a: 0 },
    { q: "¿Cuál es una limitación o dificultad de implementación de la norma?",
      opts: ["Sus orientaciones son generales y deben adaptarse a cada organización",
             "Es demasiado específica zona por zona",
             "No necesita recursos",
             "Es aplicable solo a un sector"], a: 0 },
    { q: "¿Qué puede demandar la implementación de ISO/IEC 27002?",
      opts: ["Coordinación, recursos y participación de diferentes áreas",
             "Ningún esfuerzo", "Solo la compra de un antivirus",
             "Una única reunión"], a: 0 },
    { q: "¿Qué tipo de organización puede tener mayores dificultades para implementar todos los controles?",
      opts: ["La que tiene recursos económicos, humanos o técnicos limitados",
             "La que tiene muchos recursos", "La que ya está certificada",
             "La que no tiene empleados"], a: 0 },
    { q: "Según la resolución, ¿qué se necesita para que la norma funcione de verdad?",
      opts: ["Que sea algo constante, con personas, procesos y tecnología trabajando juntos",
             "Aplicarla una sola vez y olvidarla",
             "Comprar más servidores", "Contratar un solo consultor"], a: 0 },
    { q: "¿Qué tipo de control NO corresponde a los ejemplos de la norma?",
      opts: ["El control del clima laboral", "El control de acceso",
             "La autenticación segura", "Las copias de respaldo"], a: 0 }
  ]
};

module.exports = { CATS, QUESTIONS };